// ===================================
// gallery.js
// ไฟล์นี้โหลดและแสดงภาพใน Gallery พร้อม modal รายละเอียด
// ===================================
import { CONFIG, apiFetch, escapeHtml, openModal, closeModal } from './shared.js';
const demoImages = [{ id: 'demo-1', image_url: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=800&q=80', prompt: 'neon city after rain, cinematic lighting', type: 'txt2img', created_at: '2026-09-20T09:30:00Z', status: 'completed', parameters: { style: 'Cyberpunk', steps: 32, resolution: '768x768' } }, { id: 'demo-2', image_url: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?auto=format&fit=crop&w=800&q=80', prompt: 'astronaut floating above a quiet planet', type: 'txt2img', created_at: '2026-09-18T15:10:00Z', status: 'completed', parameters: { style: 'Realistic', steps: 28, resolution: '1024x768' } }, { id: 'demo-3', image_url: 'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=800&q=80', prompt: 'abstract orange and teal energy', type: 'img2img', created_at: '2026-09-15T11:45:00Z', status: 'completed', parameters: { style: 'Oil Painting', steps: 30, resolution: '768x768' } }];
// โหลดข้อมูลจาก API หรือใช้ mock data แล้วนำไป render เป็น gallery grid
export async function loadGallery() { let records = demoImages; if (!CONFIG.USE_DEMO_MODE) records = await apiFetch(CONFIG.ENDPOINTS.GALLERY); const latest = JSON.parse(localStorage.getItem('forge_last_result') || 'null'); if (latest) records = [latest, ...records]; renderGallery(records); }
// สร้าง card และผูก click เพื่อเปิดรายละเอียดของภาพใน modal
function renderGallery(records) { const grid = document.getElementById('gallery-grid'); if (!grid) return; grid.innerHTML = records.map(item => `<article class="gallery-card" tabindex="0" data-gallery-id="${item.id}"><img src="${item.image_url}" alt="ภาพจาก prompt: ${escapeHtml(item.prompt)}" loading="lazy"><div class="gallery-card-body"><span class="badge">${item.type}</span><p>${escapeHtml(item.prompt)}</p><small>${new Date(item.created_at).toLocaleDateString('th-TH')}</small></div></article>`).join(''); grid.querySelectorAll('[data-gallery-id]').forEach(card => card.addEventListener('click', () => { const item = records.find(record => record.id === card.dataset.galleryId); openModal(`<img class="modal-image" src="${item.image_url}" alt="${escapeHtml(item.prompt)}"><h2>${escapeHtml(item.prompt)}</h2><p class="muted">${item.type} · ${new Date(item.created_at).toLocaleString('th-TH')}</p><pre>${escapeHtml(JSON.stringify(item.parameters, null, 2))}</pre>`); })); }
document.addEventListener('click', event => { if (event.target.matches('[data-close-modal], .modal-backdrop')) closeModal(); });