// ===================================
// history.js
// ไฟล์นี้แสดงประวัติการสร้างภาพ พร้อม filter, pagination และ modal
// ===================================
import { CONFIG, apiFetch, escapeHtml, openModal, closeModal } from './shared.js';
const demoHistory = [{ id: 'h1', prompt: 'neon city after rain, cinematic lighting', type: 'txt2img', created_at: '2026-09-20T09:30:00Z', status: 'completed', parameters: { style: 'Cyberpunk', steps: 32, cfg_scale: 7 } }, { id: 'h2', prompt: 'make the armor glow with teal energy', type: 'img2img', created_at: '2026-09-18T15:10:00Z', status: 'completed', parameters: { strength: 0.72, resolution: '768x768' } }, { id: 'h3', prompt: 'quiet mountain observatory under stars', type: 'txt2img', created_at: '2026-09-12T20:20:00Z', status: 'completed', parameters: { style: 'Realistic', steps: 28, cfg_scale: 6 } }]; let records = demoHistory; let page = 1; const pageSize = 5;
// โหลดประวัติจาก API หรือใช้รายการจำลอง แล้วแสดงหน้าปัจจุบัน
export async function loadHistory() { if (!CONFIG.USE_DEMO_MODE) records = await apiFetch(CONFIG.ENDPOINTS.HISTORY); renderHistory(); }
// กรองข้อมูล แบ่งหน้า และผูก click เพื่อเปิดรายละเอียด prompt/parameters
function renderHistory() { const type = document.getElementById('history-type')?.value || 'all'; const date = document.getElementById('history-date')?.value || ''; const filtered = records.filter(item => (type === 'all' || item.type === type) && (!date || item.created_at.startsWith(date))); const visible = filtered.slice((page - 1) * pageSize, page * pageSize); const list = document.getElementById('history-list'); list.innerHTML = visible.length ? visible.map(item => `<article class="history-row" data-history-id="${item.id}"><span class="history-icon">${item.type === 'txt2img' ? '🎨' : '🪄'}</span><div><strong>${escapeHtml(item.prompt)}</strong><p>${item.type} · ${new Date(item.created_at).toLocaleString('th-TH')}</p></div><span class="status-pill">${item.status}</span></article>`).join('') : '<p class="empty-state">ยังไม่มีรายการที่ตรงกับตัวกรอง</p>'; list.querySelectorAll('[data-history-id]').forEach(row => row.addEventListener('click', () => { const item = records.find(record => record.id === row.dataset.historyId); openModal(`<h2>${escapeHtml(item.prompt)}</h2><p class="muted">${item.type} · ${new Date(item.created_at).toLocaleString('th-TH')}</p><pre>${escapeHtml(JSON.stringify(item.parameters, null, 2))}</pre>`); })); const maxPage = Math.max(1, Math.ceil(filtered.length / pageSize)); document.getElementById('history-page').textContent = `${page} / ${maxPage}`; document.getElementById('history-prev').disabled = page === 1; document.getElementById('history-next').disabled = page >= maxPage; }
document.addEventListener('change', event => { if (event.target.matches('#history-type, #history-date')) { page = 1; renderHistory(); } }); document.addEventListener('click', event => { if (event.target.matches('[data-close-modal], .modal-backdrop')) closeModal(); if (event.target.id === 'history-prev') { page--; renderHistory(); } if (event.target.id === 'history-next') { page++; renderHistory(); } });